
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  template:
    spec:
      containers:
      - name: sample-fastapi-container
        env:
        - name: ENV
          value: dev
